Lesson 5
PerkProject/react_example pull request #5
Opened 2018-09-17 20:32 UTC by Perkir

2018-09-18 15:30 UTC, index01d requested changes

2018-09-18 15:30 UTC, index01d commented on index.js
> +ReactDOM.render( <
что-то не так с переносами

2018-09-18 15:30 UTC, index01d commented on src/components/gallery/Gallery.js
> +              {
можно было бы выделить компонент Thumbnails

2018-09-18 15:30 UTC, index01d commented on src/components/gallery/Gallery.js
> +            <ul className='list-inline'>
можно было бы выделить контейнер с контролами (Controls)

2018-09-18 15:30 UTC, index01d commented on src/components/gallery/Gallery.js
> +      <Row className='mb-2 mt-5'>
куски грида в виджетах не есть хорошо, тк ограничивают применимость виджета

2018-09-18 15:30 UTC, index01d commented on src/components/layouts/Menu.js
> +      path = productGalleryPath(id)
;?

2018-09-18 15:30 UTC, index01d commented on src/components/layouts/Menu.js
> +    let path = galleryPath()
;?
p.s.: eslint может помочь не допускать подобных разнообразий

2018-09-18 15:30 UTC, index01d commented on src/components/products/AddToBasket.js
> +      count += 1;
this.setState((state) => ({ count: state.count + 1 }) ))

иначе ты меняешь значение в состояние без вызова setState. изменения могут быть утеряны

2018-09-18 15:30 UTC, index01d commented on src/components/products/ProductCard.js
> +  id: '1',
подразумевается, что здесь будут заглушки для ситуаций, когда поля не заполнены
например:  `title: 'Без названия'`

2018-09-18 15:30 UTC, index01d commented on src/containers/BasketContainer.js
> +const BasketContainer = () => <Basket />
назначение компонента непонятно

2018-09-20 11:27 UTC, Perkir commented on src/components/gallery/Gallery.js
> +            <ul className='list-inline'>
Имеются ввиду кнопки?

2018-09-20 11:27 UTC, Perkir commented on src/components/gallery/Gallery.js
> +      <Row className='mb-2 mt-5'>
а куда их лучше вынести?

2018-09-21 13:32 UTC, index01d commented on src/components/gallery/Gallery.js
> +      <Row className='mb-2 mt-5'>
в компонент, который находится выше по иерархии

2018-09-21 13:33 UTC, index01d commented on src/components/gallery/Gallery.js
> +            <ul className='list-inline'>
да

2018-09-21 13:34 UTC, index01d requested changes

2018-09-21 13:34 UTC, index01d commented on src/components/gallery/Thumbnails.js
> +        onClick={() => this.setActiveIndex(index)}
откуда взялся метод здесь? вероятно не работает?

2018-09-21 13:34 UTC, index01d commented on src/containers/BasketContainer.js
> +//import React, { Component } from 'react';
следует избегать закомментированного кода в репозитории

2018-09-24 07:48 UTC, index01d approved these changes

2018-09-24 08:01 UTC, merged